# Generated by Django 5.0 on 2024-01-07 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=100, verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Тип кузовы',
            },
        ),
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='марка')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренды',
            },
        ),
        migrations.CreateModel(
            name='DriveUnitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_unit', models.CharField(max_length=100, verbose_name='привод')),
            ],
            options={
                'verbose_name': 'привод',
                'verbose_name_plural': 'приводы',
            },
        ),
        migrations.CreateModel(
            name='EngineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=100, verbose_name='двигатель')),
            ],
            options={
                'verbose_name': 'двигатель',
                'verbose_name_plural': 'двигатели',
            },
        ),
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo', verbose_name='Поколение')),
            ],
            options={
                'verbose_name': 'Поколение',
                'verbose_name_plural': 'Поколения',
            },
        ),
        migrations.CreateModel(
            name='ImgCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='img')),
            ],
            options={
                'verbose_name': 'img',
                'verbose_name_plural': 'img',
            },
        ),
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='модель')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
            },
        ),
        migrations.CreateModel(
            name='ModificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.FloatField(verbose_name='модификация')),
            ],
            options={
                'verbose_name': 'модификация',
                'verbose_name_plural': 'модификации',
            },
        ),
        migrations.CreateModel(
            name='SteeringWheelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steering_wheel', models.CharField(max_length=100, verbose_name='руль')),
            ],
            options={
                'verbose_name': 'руль',
                'verbose_name_plural': 'руль',
            },
        ),
        migrations.CreateModel(
            name='TransmissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=100, verbose_name='Коробка передач')),
            ],
            options={
                'verbose_name': 'Коробка передач',
                'verbose_name_plural': 'Коробка передачи',
            },
        ),
        migrations.CreateModel(
            name='YearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_issue', models.IntegerField(verbose_name='год выпуска')),
            ],
            options={
                'verbose_name': 'год выпуска',
                'verbose_name_plural': 'год выпуски',
            },
        ),
        migrations.CreateModel(
            name='CarAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('color', models.CharField(choices=[('черный', 'черный'), ('белый', 'белый'), ('синий', 'синий'), ('зеленый', 'зеленый'), ('серебристый', 'серебристый'), ('серый', 'серый'), ('бежевый', 'бежевый'), ('бирюзовый', 'бирюзовый'), ('бордовый', 'бордовый'), ('бронза', 'бронза'), ('вишня', 'вишня'), ('голубой', 'голубой'), ('коричневый', 'коричневый'), ('золотистый', 'золотистый'), ('жёлтый', 'жёлтый'), ('красный', 'красный'), ('оранжевый', 'оранжевый'), ('розовый', 'розовый'), ('сиреневый', 'сиреневый'), ('фиолетовый', 'фиолетовый'), ('хамелеон', 'хамелеон'), ('баклажан', 'баклажан')], default=2000, verbose_name='Цвет')),
                ('body_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_ads_body_type', to='car.bodytypecategory', verbose_name='Тип кузова')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_ads_brand', to='car.brandcategory', verbose_name='марка')),
                ('drive_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_ads_drive_unit', to='car.driveunitcategory', verbose_name='привод')),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_ads_engine', to='car.enginecategory', verbose_name='двигатель')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_ads_image', to='car.imagecategory', verbose_name='Поколение')),
                ('img', models.ManyToManyField(related_name='car_ads_images', to='car.imgcategory', verbose_name='Фотографии')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_ads_model', to='car.modelcategory', verbose_name='модель')),
                ('modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_ads_modification', to='car.modificationcategory', verbose_name='модификация')),
                ('steering_wheel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_ads_steering_wheel', to='car.steeringwheelcategory', verbose_name='руль')),
                ('transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_ads_transmission', to='car.transmissioncategory', verbose_name='Коробка передач')),
                ('year_of_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_ads_year_of_issue', to='car.yearcategory', verbose_name='год выпуска')),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ads',
            },
        ),
    ]
