# Generated by Django 5.0 on 2024-01-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearcategory',
            name='year_of_issue',
            field=models.PositiveSmallIntegerField(default=1800, verbose_name='год выпуска'),
        ),
    ]
